version: "3"

services:
  app:
    build:
      context: ./app
    env_file:
      - ./app/.env
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 3000 --reload
    container_name: creditcard-app
    networks:
      - backend-network
    tty: true
    volumes:
      - ./app:/app
      - ./app/database/
    ports:
      - "3000:3000"
networks:
  backend-network:
    driver: bridge
